export const CART_ACTION_TYPES = {
	SET_CART_ACTIVE: 'SET_CART_ACTIVE',
	SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
	SET_CART_ITEMS: 'SET_CART_ITEMS',
	SET_CART_COUNT: 'SET_CART_COUNT',
	SET_CART_TOTAL: 'SET_CART_TOTAL',
	CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
};
